// components/drop-zone.tsx
"use client"

import { useRef, useState, useCallback } from "react"
import { Upload } from "lucide-react"
import { useI18n } from "@/lib/i18n-context"

const INPUT_FORMATS = ["JPEG", "PNG", "WebP", "AVIF", "HEIC", "GIF", "BMP", "SVG"]

/** MIME types / extensions that browsers may not set correctly */
const IMAGE_EXTENSIONS = /\.(jpe?g|png|gif|bmp|svg|webp|avif|heic|heif|tiff?|ico)$/i
const KNOWN_IMAGE_MIMES = /^image\//

interface DropZoneProps {
  onFile: (file: File) => void
}

export function DropZone({ onFile }: DropZoneProps) {
  const { t } = useI18n()
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [dragOver, setDragOver] = useState(false)
  const [error, setError] = useState("")

  const handleFile = useCallback(
    (f: File) => {
      // Check MIME type first, then fall back to extension for formats
      // browsers may not recognize (e.g. HEIC, TIFF)
      const isImage =
        KNOWN_IMAGE_MIMES.test(f.type) || IMAGE_EXTENSIONS.test(f.name)
      if (!isImage) {
        setError(t("dropzone.invalidFile"))
        return
      }
      setError("")
      onFile(f)
    },
    [onFile, t]
  )

  const onDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault()
      setDragOver(false)
      const f = e.dataTransfer?.files[0]
      if (f) handleFile(f)
    },
    [handleFile]
  )

  const onFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const f = e.target.files?.[0]
      if (f) handleFile(f)
    },
    [handleFile]
  )

  return (
    <div
      className="flex items-center justify-center px-4"
      style={{
        minHeight:
          "calc(100dvh - var(--header-height, 4rem) - var(--footer-height, 3rem))",
      }}
    >
      <div className="w-full max-w-xl">
        <div
          className={`border-2 border-dashed rounded-2xl p-16 text-center cursor-pointer transition-all duration-200 select-none ${
            dragOver
              ? "border-primary bg-primary/5 scale-[1.01]"
              : "border-border hover:border-primary hover:bg-primary/5"
          }`}
          onDragOver={(e) => {
            e.preventDefault()
            setDragOver(true)
          }}
          onDragLeave={() => setDragOver(false)}
          onDrop={onDrop}
          onClick={() => fileInputRef.current?.click()}
        >
          <div className="flex flex-col items-center gap-5">
            <div className="size-16 rounded-2xl bg-muted flex items-center justify-center">
              <Upload className="size-8 text-muted-foreground" />
            </div>
            <div>
              <p className="text-lg font-semibold text-foreground">
                {t("dropzone.title")}
              </p>
              <p className="text-sm text-muted-foreground mt-1">
                {t("dropzone.subtitle")}
              </p>
            </div>
            <div className="flex flex-wrap justify-center gap-1.5">
              {INPUT_FORMATS.map((fmt) => (
                <span
                  key={fmt}
                  className="text-xs px-2 py-0.5 rounded-full bg-muted text-muted-foreground"
                >
                  {fmt}
                </span>
              ))}
            </div>
          </div>
        </div>

        {error && (
          <p className="text-red-500 text-sm text-center mt-3">{error}</p>
        )}

        <p className="text-center text-xs text-muted-foreground mt-5 flex items-center justify-center gap-1.5">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="12"
            height="12"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="shrink-0"
          >
            <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
            <path d="M7 11V7a5 5 0 0 1 10 0v4" />
          </svg>
          {t("dropzone.privacy")}
        </p>

        <input
          ref={fileInputRef}
          type="file"
          accept="image/*,.heic,.heif,.tiff,.tif"
          className="hidden"
          onChange={onFileChange}
        />
      </div>
    </div>
  )
}

// app/components/converter/DropZone.vue
<script setup lang="ts">
const emit = defineEmits<{
  file: [file: File]
}>()

const dragOver = shallowRef(false)
const error = shallowRef('')
const fileInput = useTemplateRef<HTMLInputElement>('fileInput')

function handleFile(f: File) {
  if (!f.type.startsWith('image/')) {
    error.value = 'Please select an image file'
    return
  }
  error.value = ''
  emit('file', f)
}

function onDrop(e: DragEvent) {
  e.preventDefault()
  dragOver.value = false
  const f = e.dataTransfer?.files[0]
  if (f) handleFile(f)
}

function onFileChange(e: Event) {
  const f = (e.target as HTMLInputElement).files?.[0]
  if (f) handleFile(f)
}
</script>

<template>
  <div class="flex items-center justify-center px-4" style="min-height: calc(100vh - 130px)">
    <div class="w-full max-w-xl">
      <div
        class="border-2 border-dashed rounded-2xl p-16 text-center cursor-pointer transition-all duration-200 select-none"
        :class="dragOver
          ? 'border-primary bg-primary/5 scale-[1.01]'
          : 'border-(--ui-border) hover:border-primary hover:bg-primary/5'"
        @dragover.prevent="dragOver = true"
        @dragleave="dragOver = false"
        @drop="onDrop"
        @click="fileInput?.click()"
      >
        <div class="flex flex-col items-center gap-5">
          <div class="size-16 rounded-2xl bg-(--ui-bg-muted) flex items-center justify-center">
            <UIcon name="i-lucide-image-up" class="size-8 text-(--ui-text-muted)" />
          </div>
          <div>
            <p class="text-lg font-semibold text-(--ui-text)">Drop your image here</p>
            <p class="text-sm text-(--ui-text-muted) mt-1">or click to browse files</p>
          </div>
          <div class="flex flex-wrap justify-center gap-1.5">
            <span
              v-for="fmt in ['JPEG', 'PNG', 'WebP', 'AVIF', 'GIF', 'BMP', 'SVG']"
              :key="fmt"
              class="text-xs px-2 py-0.5 rounded-full bg-(--ui-bg-muted) text-(--ui-text-muted)"
            >
              {{ fmt }}
            </span>
          </div>
        </div>
      </div>

      <p v-if="error" class="text-red-500 text-sm text-center mt-3">{{ error }}</p>

      <p class="text-center text-xs text-(--ui-text-muted) mt-5 flex items-center justify-center gap-1.5">
        <UIcon name="i-lucide-lock" class="size-3 shrink-0" />
        Images are processed locally — never uploaded to any server
      </p>
    </div>

    <input ref="fileInput" type="file" accept="image/*" class="hidden" @change="onFileChange">
  </div>
</template>
